import type { Metadata } from "next";
import "./globals.css";
import { M_BOLD } from "./fonts";

export const metadata: Metadata = {
	manifest: "/manifest.json",
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={M_BOLD.className}>{children}</body>
		</html>
	);
}
