import type { Metadata } from "next";
import "./globals.css";
import { M_BOLD } from "./fonts";

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Botani Know",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${M_BOLD.className} bg-[#F5F5F7]`}>{children}</body>
    </html>
  );
}
